#!/bin/bash

green='\e[0;32m'
red='\e[0;31m'
purple='\e[0;35m'
cyan='\e[0;36m'
endColor='\e[0m'
item=${green}[*]${endColor}

echo ""
echo -e "${green}##################################${endColor}"
echo -e "${green}# Disabling nuk3gh0st at startup #${endColor}"
echo -e "${green}##################################${endColor}"
echo ""

echo -e "${item} Checking if SELINUX is enabled"
if [ -f /usr/sbin/semanage ]; then
	echo -e "${item} SELINUX is enabled"
	#semanage permissive -d insmod_t
	echo -e "${item} Disabling SELINUX temporarily"
	echo -e "   ${purple} cmd: setenforce 0${endColor}"
	setenforce 0
	echo ""
	
	echo -e "${item} Stopping nuk3gh0st.service"
	echo -e "   ${purple} cmd: service nuk3gh0st stop${endColor}"
	echo -n -e "${cyan}"
	service nuk3gh0st stop
	echo -n -e "${endColor}"
	echo ""
	
	echo -e "${item} Disabling nuk3gh0st.service"
	echo -e "   ${purple} cmd: systemctl disable nuk3gh0st.service${endColor}"
	echo -n -e "${cyan}"
	systemctl disable nuk3gh0st.service
	echo -n -e "${endColor}"
	echo ""
	
	echo -e "${item} Unhiding nuk3gh0st LKM rootkit (making visible with lsmod)"
	echo -e "   ${purple} cmd: nuk3gh0st --unhide${endColor}"
	nuk3gh0st --unhide
	echo ""
	
	echo -e "${item} Unprotecting nuk3ghost LKM rootkit"
	echo -e "   ${purple} cmd: nuk3gh0st --unprotect${endColor}"
	nuk3gh0st --unprotect
	echo ""
	
	echo -e "${item} Unloading nuk3gh0st LKM rootkit"
	echo -e "   ${purple} cmd: rmmod rootkit.ko${endColor}"
	rmmod rootkit.ko > /dev/null 2>&1
	echo ""
	
	systemctl disable nuk3gh0st.service
	echo -e "${item} Reenabling SELINUX"
	echo -e "   ${purple} cmd: setenforce 1${endColor}"
	setenforce 1
	echo ""
	
else
	echo -e "${item} SELINUX is disabled"
	echo -e "${item} Stopping nuk3gh0st.service"
	echo -e "   ${purple} cmd: service nuk3gh0st stop${endColor}"
	echo -n -e "${cyan}"
	service nuk3gh0st stop
	echo -n -e "${endColor}"
	echo ""
	
	echo -e "${item} Disabling nuk3gh0st.service"
	echo -e "   ${purple} cmd: systemctl disable nuk3gh0st.service${endColor}"
	echo -n -e "${cyan}"
	systemctl disable nuk3gh0st.service
	echo -n -e "${endColor}"
	echo ""
	
	echo -e "${item} Unhiding nuk3gh0st LKM rootkit (making visible with lsmod)"
	echo -e "   ${purple} cmd: nuk3gh0st --unhide${endColor}"
	nuk3gh0st --unhide
	echo ""
	
	echo -e "${item} Unprotecting nuk3ghost LKM rootkit"
	echo -e "   ${purple} cmd: nuk3gh0st --unprotect${endColor}"
	nuk3gh0st --unprotect
	echo ""
	
	echo -e "${item} Unloading nuk3gh0st LKM rootkit"
	echo -e "   ${purple} cmd: rmmod rootkit.ko${endColor}"
	rmmod rootkit.ko > /dev/null 2>&1
	echo ""
	
fi

echo -e "${item} Removing nuk3gh0st.service"
echo -e "   ${purple} cmd: rm /lib/systemd/system/nuk3gh0st.service${endColor}"
rm /lib/systemd/system/nuk3gh0st.service
echo ""
