#!/bin/bash
echo "###################################"
echo "# Unloading nuk3gh0st LKM rootkit #"
echo "###################################"
echo ""
echo "Unhiding nuk3gh0st LKM rootkit (making visible with lsmod)"
echo "cmd: nuk3gh0st --unhide"
nuk3gh0st --unhide
echo "Unprotecting nuk3ghost LKM rootkit"
echo "cmd: nuk3gh0st --unprotect"
nuk3gh0st --unprotect
echo "Checking if SELINUX is enabled..."
if [ -f /usr/sbin/setenforce ]; then
	echo "SELINUX is enabled"
	echo "Disabling SELINUX temporarily"
	echo "cmd: setenforce 0"
	setenforce 0
	echo "Unloading nuk3gh0st LKM rootkit"
	echo "cmd: rmmod rootkit.ko"
	rmmod rootkit.ko
	echo "Reenabling SELINUX"
	echo "cmd: setenforce 1"
	setenforce 1
else
	echo "SELINUX is disabled"
	echo "Unloading nuk3gh0st LKM rootkit"
	echo "cmd: rmmod rootkit.ko"
	rmmod rootkit.ko
fi


